name: dart_smarteam
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://t.me/nimec77

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  dartz: ^0.10.0
  ffi: ^1.1.2

dev_dependencies:
  test: ^1.17.12
  very_good_analysis: ^2.3.0
