name: smarteam
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://t.me/nimec77

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  dartz: ^0.10.0-nullsafety.2
  ffi: ^1.1.2
  smart_compute:
    git:
      url: https://github.com/nimec77/smart_compute.git

dev_dependencies:
  very_good_analysis: ^2.1.2
  test: ^1.17.10
  